[package]
name = "rusty-xr-broker-client-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rusty-xr-broker-model = { path = "../../crates/rusty-xr-broker-model", features = ["serde"] }
serde_json.workspace = true

[lints]
workspace = true
